pipeline:
    name: trial-ci-cd
    identifier: trialcicd
    projectIdentifier: assignment01
    orgIdentifier: Assignment
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: githubassignmentorg
                repoName: firstdrone
                build: <+input>
    stages:
        - stage:
              name: Build Stage
              identifier: Build_Stage
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesHosted
                      spec:
                          identifier: k8s-hosted-infra
                  execution:
                      steps:
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: docker-build-push
                                identifier: dockerbuildpush
                                spec:
                                    connectorRef: dockerconnectornew
                                    repo: sreelk589/demotrial
                                    tags:
                                        - latest
        - stage:
              name: deploy
              identifier: deploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: newservice
                      serviceDefinition:
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: manifest
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: githubassignmentorg
                                                    gitFetchType: Branch
                                                    paths:
                                                        - content/en/examples/application/nginx-app.yaml
                                                    branch: main
                                            skipResourceVersioning: false
                          type: Kubernetes
                  infrastructure:
                      environmentRef: newenvironment
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: newconnectorkube
                              namespace: harness-delegate-ng
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
